### PR TITLE
Building with Backgrounds and Gradients

### PR DESCRIPTION
**Pull request by tacodtripe**
# Clone of the old Apple webpage
In this project I:
- Exercised the linear-gradient attribute to style the color of the elements.
- Worked with the background property to embed a background image.
- Practiced all the previous HTML/CSS concepts to build a professional webpage.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### This PR is under Review by [TSE] _Temitayo Adeleke_

**Comment by lekegitrepo** [comment]
### Hi @tacodtripe  👍 
### The project looks good but there are some important requirements that are missing. Check my comments below.

**_1. Fix the stickler errors._**

**_2. The page suppose to occupy the width of the browser(avoid horizontal scroll bar)._**

**_This is the original:_**

image

**_This is your version:_**

image

**_3. As mentioned: Elements should be aligned with float and  flex or grid_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

**_4. The footer of your page should have space like the origin._**

**_This is the original:_**

image

**_This is your version:_**

image

**_Kindly make these changes and submit for review_**

If you have any doubt or question contact me on slack.

### Reviewed by: **_Temitayo Adeleke_**

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require Changes

**Review by nikasulo — APPROVED** [review]
# Great work @tacodtripe! :rocket:
Please merge and keep moving forward! Your project looks really great, however, there are a few changes I'd like to propose that could improve it and make it more in-line with the requirements for this project, please consider them :ok_hand: 

#### [OPTIONAL] NavBar
Please consider your navigation bar, it looks really nice and you have implemented the gradient properly, however, the size is a little bit disproportionate, please compare yours with the original site and make changes as you see fit!

#### [OPTIONAL] Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
